swagger: "2.0"
info:
  title: Blog Service
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - blog
      summary: list blog
      description: List all the blogs
      operationId: blog#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredBlogResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogListDbErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - blog
      summary: create blog
      description: Add a new blog
      operationId: blog#create
      parameters:
      - name: Authorization
        in: header
        description: Access github token
        required: true
        type: string
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogCreateRequestBody'
          required:
          - blog
      responses:
        "201":
          description: Created response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/BlogCreateInvalidTokenResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogCreateDbErrorResponseBody'
      schemes:
      - http
  /{id}:
    get:
      tags:
      - blog
      summary: show blog
      description: Show blog based on the id given
      operationId: blog#show
      parameters:
      - name: id
        in: path
        description: ID of the blog to be fetched
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BlogShowResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogShowDbErrorResponseBody'
      schemes:
      - http
    delete:
      tags:
      - blog
      summary: remove blog
      description: Delete a blog
      operationId: blog#remove
      parameters:
      - name: id
        in: path
        description: ID of blog to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogRemoveDbErrorResponseBody'
      schemes:
      - http
  /{id}/comments:
    patch:
      tags:
      - blog
      summary: add blog
      description: Add a new comment for a blog
      operationId: blog#add
      parameters:
      - name: id
        in: path
        description: Id of the blog
        required: true
        type: integer
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogAddRequestBody'
          required:
          - comments
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogAddDbErrorResponseBody'
      schemes:
      - http
  /oauth/redirect:
    post:
      tags:
      - oauth
      summary: oauth oauth
      description: Github authentication to post a new blog
      operationId: oauth#oauth
      parameters:
      - name: OauthRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/OauthOauthRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/OauthOauthInternalErrorResponseBody'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /user:
    post:
      tags:
      - user
      summary: create user
      description: Add a new blog
      operationId: user#create
      parameters:
      - name: Authorization
        in: header
        description: Access github token
        required: true
        type: string
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserCreateRequestBody'
          required:
          - user
      responses:
        "201":
          description: Created response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/UserCreateInvalidTokenResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserCreateDbErrorResponseBody'
      schemes:
      - http
  /users:
    get:
      tags:
      - user
      summary: list user
      description: List all the users
      operationId: user#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/UserResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserListDbErrorResponseBody'
      schemes:
      - http
definitions:
  BlogAddDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogAddRequestBody:
    title: BlogAddRequestBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentRequestBody'
    example:
      comments:
        comment: Iure velit.
        id: 8779553980399303872
    required:
    - comments
  BlogCreateDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogCreateInvalidTokenResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: User token not valid (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogCreateRequestBody:
    title: BlogCreateRequestBody
    type: object
    properties:
      blog:
        $ref: '#/definitions/BlogRequestBody'
    example:
      blog:
        comments:
        - comment: Iure velit.
          id: 8779553980399303872
        - comment: Iure velit.
          id: 8779553980399303872
        - comment: Iure velit.
          id: 8779553980399303872
        name: Nihil consequatur sunt asperiores.
    required:
    - blog
  BlogListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogRemoveDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogRequestBody:
    title: BlogRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentRequestBody'
        description: Blog will have multiple comments
        example:
        - comment: Iure velit.
          id: 8779553980399303872
        - comment: Iure velit.
          id: 8779553980399303872
        - comment: Iure velit.
          id: 8779553980399303872
      name:
        type: string
        description: Name of person
        example: Non qui corporis aspernatur ut aspernatur cumque.
    description: A Blog describes a blog retrieved by the storage service.
    example:
      comments:
      - comment: Iure velit.
        id: 8779553980399303872
      - comment: Iure velit.
        id: 8779553980399303872
      - comment: Iure velit.
        id: 8779553980399303872
      - comment: Iure velit.
        id: 8779553980399303872
      name: Saepe voluptas necessitatibus labore nam minus.
    required:
    - name
    - comments
  BlogShowDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogShowResponseBody:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponseBody'
        description: Blog with multiple comments
        example:
        - comment: Iste et eos voluptatem architecto necessitatibus id.
          id: 12653072017091130437
        - comment: Iste et eos voluptatem architecto necessitatibus id.
          id: 12653072017091130437
        - comment: Iste et eos voluptatem architecto necessitatibus id.
          id: 12653072017091130437
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 15195045545377320037
        format: int64
      name:
        type: string
        description: Name of person
        example: Asperiores ad dolorem corporis amet.
    description: ShowResponseBody result type (default view)
    example:
      comments:
      - comment: Iste et eos voluptatem architecto necessitatibus id.
        id: 12653072017091130437
      - comment: Iste et eos voluptatem architecto necessitatibus id.
        id: 12653072017091130437
      id: 4655761708883978709
      name: Consequatur voluptatem vel aut qui velit.
    required:
    - id
    - name
    - comments
  CommentRequestBody:
    title: CommentRequestBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Itaque odit.
      id:
        type: integer
        description: ID of a comment
        example: 8871157750952403261
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Enim rerum sed.
      id: 13461490561757903450
    required:
    - comment
  OauthOauthInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  OauthOauthRequestBody:
    title: OauthOauthRequestBody
    type: object
    properties:
      token:
        type: string
        description: Access github token
        example: Saepe qui dolor autem.
    example:
      token: Rerum molestiae et iusto aut vel temporibus.
  StoredBlogResponse:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponse'
        description: Blog with multiple comments
        example:
        - comment: Est placeat.
          id: 10907177444388360805
        - comment: Est placeat.
          id: 10907177444388360805
        - comment: Est placeat.
          id: 10907177444388360805
        - comment: Est placeat.
          id: 10907177444388360805
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 8745972867205850437
        format: int64
      name:
        type: string
        description: Name of person
        example: Sed est dolor magni quia veritatis.
    description: A Blog describes a blog retrieved by the storage service. (default
      view)
    example:
      comments:
      - comment: Est placeat.
        id: 10907177444388360805
      - comment: Est placeat.
        id: 10907177444388360805
      - comment: Est placeat.
        id: 10907177444388360805
      - comment: Est placeat.
        id: 10907177444388360805
      id: 1929732356760849941
      name: Cumque quia aut explicabo et molestiae.
    required:
    - id
    - name
    - comments
  StoredCommentResponse:
    title: StoredCommentResponse
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Commodi corporis rerum deleniti architecto est.
      id:
        type: integer
        description: ID of a comment
        example: 18055132719716177568
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Possimus asperiores.
      id: 11230772451226272559
    required:
    - id
    - comment
  StoredCommentResponseBody:
    title: StoredCommentResponseBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Nam aspernatur deserunt.
      id:
        type: integer
        description: ID of a comment
        example: 4962304183412655930
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Provident necessitatibus architecto ipsa.
      id: 7305839890619553198
    required:
    - id
    - comment
  UserCreateDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateInvalidTokenResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: User token not valid (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateRequestBody:
    title: UserCreateRequestBody
    type: object
    properties:
      user:
        $ref: '#/definitions/UserRequestBody'
    example:
      user:
        age: 2340686031751127884
        class: Minus soluta aut dolorum fuga.
        id: 9607508899083994649
        name: Provident perspiciatis accusamus vel nam.
    required:
    - user
  UserListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserRequestBody:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-user; view=default'
    type: object
    properties:
      age:
        type: integer
        description: Age of user
        example: 5613213975677734833
        format: int64
      class:
        type: string
        description: Class of user
        example: Voluptatum recusandae.
      id:
        type: integer
        description: ID is the unique id of the user
        example: 1853529099852083550
        format: int64
      name:
        type: string
        description: Name of user
        example: Sit optio officiis sint eos.
    description: A User describes a user retrieved by the storage service. (default
      view)
    example:
      age: 11417456082914936648
      class: Vel dolores quis eligendi beatae consequatur velit.
      id: 17297640056316739497
      name: Repudiandae numquam voluptatum nisi inventore laudantium et.
    required:
    - name
    - age
    - class
  UserResponse:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-user; view=default'
    type: object
    properties:
      age:
        type: integer
        description: Age of user
        example: 723926494176722675
        format: int64
      class:
        type: string
        description: Class of user
        example: Enim veniam libero aperiam.
      id:
        type: integer
        description: ID is the unique id of the user
        example: 16345046108880669643
        format: int64
      name:
        type: string
        description: Name of user
        example: Aut magnam quia quibusdam architecto sint.
    description: A User describes a user retrieved by the storage service. (default
      view)
    example:
      age: 8040078393600807519
      class: Ipsa officiis.
      id: 7736250100465945102
      name: Neque asperiores et nostrum.
    required:
    - name
    - age
    - class
